Cleanup
adfinis/cookiecutter-django-json-api pull request #400
Opened 2024-08-19 08:42 UTC by c0rydoras

2024-08-19 12:49 UTC, open-dynaMIX requested changes
Looks good :tada:

Why no `.gitlab-ci.yml` anymore? :cry:

2024-08-19 12:50 UTC, c0rydoras commented
it uses python 3.6 so i thought that wasn't used anymore

2024-08-19 12:56 UTC, open-dynaMIX commented
> it uses python 3.6 so i thought that wasn't used anymore

I seem to have missed this in #389.

2024-08-19 12:57 UTC, c0rydoras commented
i'd also be in favour of making the template compatible with not just gitlab, but also github

2024-08-19 12:57 UTC, c0rydoras commented
AFAIK that could be some choice variable

2024-08-19 13:24 UTC, open-dynaMIX commented
Agree, I was thinking about the same. But this is out of scope for a cleanup PR. Just restore the previous functionality here. I think most of the time, the CI config will have to be touched anyway, but it's nice to already have a simple generated structure for it.

Feel free to open an issue for supporting GH actions.

2024-08-19 14:05 UTC, c0rydoras commented
`.gitlab-ci.yml` is now restored

2026-05-28 09:24 UTC, open-dynaMIX commented
@c0rydoras Sorry, I totally forgot about that. Could you please rebase and then we can finally merge this 2 years later :laughing: 
There are not a lot of commits since then, so rebasing should be rather easy :tm:

2026-05-28 11:02 UTC, open-dynaMIX approved these changes

2026-05-28 11:03 UTC, merged